### ISSUE TITLE
Can't start a jetty server

### ISSUE THREAD

**Issue by andreiwow2** [SummerSun/vscode-jetty#30]
```
[jetty-distribution-9.4.12.v20180830]: WARN  [jetty-distribution-9.4.12.v20180830]: : [jetty-distribution-9.4.12.v20180830]: System properties and/or JVM args set.  Consider using --dry-run or --exec[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:26.910:INFO::main: Logging initialized @1219ms to org.eclipse.jetty.util.log.StdErrLog[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:27.489:WARN::main: demo test-realm is deployed. DO NOT USE IN PRODUCTION![jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:27.509:INFO:oejs.Server:main: jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_181-b13
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:27.525:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/webapps/] at interval 1[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:27.782:WARN:oeja.AnnotationParser:main: Unknown asm implementation version, assuming version 393216[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:27.865:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=79ms[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.147:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.148:INFO:oejs.session:main: No SessionScavenger set, using defaults[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.150:INFO:oejs.session:main: node0 Scavenging every 600000ms[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.251:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@52feb982{rp-deals-1.0-SNAPSHOT,/rp-deals-1.0-SNAPSHOT,file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/webapps/rp-deals-1.0-SNAPSHOT/,AVAILABLE}{C:\Users\andre\AppData\Roaming\Code\User\workspaceStorage\8391fdd9e1c0ebd0747333f6b6bc8522\SummerSun.vscode-jetty\jetty\jetty-distribution-9.4.12.v20180830\webapps\rp-deals-1.0-SNAPSHOT}[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.344:WARN:oeja.AnnotationParser:main: Unknown asm implementation version, assuming version 393216
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.365:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=20ms
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.514:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@7a765367{ROOT,/,file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/webapps/ROOT/,AVAILABLE}{C:\Users\andre\AppData\Roaming\Code\User\workspaceStorage\8391fdd9e1c0ebd0747333f6b6bc8522\SummerSun.vscode-jetty\jetty\jetty-distribution-9.4.12.v20180830\webapps\ROOT}[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.548:INFO:oejs.AbstractConnector:main: Started ServerConnector@4c402120{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.575:INFO:oejus.SslContextFactory:main: x509=X509@4c12331b(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@7586beff[provider=null,keyStore=file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/etc/keystore,trustStore=file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/etc/keystore]
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.576:INFO:oejus.SslContextFactory:main: x509=X509@3b69e7d1(mykey,h=[],w=[]) for SslContextFactory@7586beff[provider=null,keyStore=file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/etc/keystore,trustStore=file:///C:/Users/andre/AppData/Roaming/Code/User/workspaceStorage/8391fdd9e1c0ebd0747333f6b6bc8522/SummerSun.vscode-jetty/jetty/jetty-distribution-9.4.12.v20180830/etc/keystore]
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.905:INFO:oejs.AbstractConnector:main: Started ServerConnector@2e377400{SSL,[ssl, http/1.1]}{0.0.0.0:8443}[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 2018-10-13 00:44:28.906:WARN:oejx.XmlConfiguration:main: 
java.lang.IllegalStateException: Config does not exist: file:///D:/Programming/Microsoft%20VS%20Code/etc/realm.properties
	at org.eclipse.jetty.security.PropertyUserStore.loadUsers(PropertyUserStore.java:253)
	at org.eclipse.jetty.security.PropertyUserStore.doStart(PropertyUserStore.java:329)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:192)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:486)
	at org.eclipse.jetty.start.Main.main(Main.java:77)[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: java.lang.reflect.InvocationTargetException[jetty-distribution-9.4.12.v20180830]: 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:486)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
[jetty-distribution-9.4.12.v20180830]: Caused by: java.lang.IllegalStateException: Config does not exist: file:///D:/Programming/Microsoft%20VS%20Code/etc/realm.properties
	at org.eclipse.jetty.security.PropertyUserStore.loadUsers(PropertyUserStore.java:253)
	at org.eclipse.jetty.security.PropertyUserStore.doStart(PropertyUserStore.java:329)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:192)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)
[jetty-distribution-9.4.12.v20180830]: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	... 7 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:486)[jetty-distribution-9.4.12.v20180830]: 
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.lang.IllegalStateException: Config does not exist: file:///D:/Programming/Microsoft%20VS%20Code/etc/realm.properties
	at org.eclipse.jetty.security.PropertyUserStore.loadUsers(PropertyUserStore.java:253)
[jetty-distribution-9.4.12.v20180830]: 	at org.eclipse.jetty.security.PropertyUserStore.doStart(PropertyUserStore.java:329)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:192)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)[jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]: 	at java.security.AccessController.doPrivileged(Native Method)[jetty-distribution-9.4.12.v20180830]: 
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	... 7 more[jetty-distribution-9.4.12.v20180830]: 

[jetty-distribution-9.4.12.v20180830]: Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs][jetty-distribution-9.4.12.v20180830]: 
[jetty-distribution-9.4.12.v20180830]:        java -jar $JETTY_HOME/start.jar --help  # for more information

```

**Comment by caiqichang** [comment]
+1 
i have this problem too.
what is the  **/Microsoft VS Code/etc/realm.properties**  ?

**Comment by caiqichang** [comment]
> +1
> i have this problem too.
> what is the **/Microsoft VS Code/etc/realm.properties** ?

i create a blank file(/Microsoft VS Code/etc/realm.properties) and it works ! but why ?

**Comment by PaulFelge** [comment]
worked for me. Wonder the same: "but why?"

> > +1
> > i have this problem too.
> > what is the **/Microsoft VS Code/etc/realm.properties** ?
> 
> i create a blank file(/Microsoft VS Code/etc/realm.properties) and it works ! but why ?

**Comment by khokhani** [comment]
I don't have write access of VS Code installation folder i.e.  C:/Programming/Microsoft%20VS%20Code/ on my windows machine.

Is there any way to configure Jetty to check etc/realm.properties file at other location?

**Comment by KhaymanHung** [comment]
create /Microsoft VS Code/etc/realm.properties
worked for me.
"but why?"
